
FROM ubuntu:22.04

RUN apt-get update \
 && apt install -y unzip curl git openjdk-18-jre-headless maven

## Install Planetiler
WORKDIR /src

RUN git clone --branch v0.7.0 --recurse-submodules https://github.com/onthegomap/planetiler.git
ADD https://github.com/onthegomap/planetiler/archive/refs/tags/v0.7.0.tar.gz planetiler.tar.gz
RUN tar zxvf planetiler.tar.gz && mv planetiler-0.7.0 planetiler

WORKDIR /src/planetiler

##RUN git submodule update --init
